name: publish
on:
  workflow_run:
    workflows: [tests]
    types:
      - completed
jobs:
  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '8.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install --legacy-bundling
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
